### ISSUE TITLE
log4j 오류없이 잘 동작들 하십니까??

### ISSUE THREAD

**Issue by bbubbush** [FourTeamProject/pikachu_tdd#15]
------------------------------------------------------------------------
[log 사용할 때]
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

private static Logger logger = LoggerFactory.getLogger(this.class);

------------------------------------------------------------------------
[pom.xml]

<dependency>
    <groupId>log4j</groupId>
    <artifactId>log4j</artifactId>
    <version>1.2.17</version>
</dependency>

------------------------------------------------------------------------

나는 pom.xml 받으면 org.apache.log4j 경로로 사용하는 jar가 받아지는데 내가 이상한가?? ㅋㅋㅋ

다들 log4j 잘 동작하는지 확인 좀 부탁합니다

**Comment by bbubbush** [comment]
pull 이후에 pom.xml 새로고침 한번 해주십쇼

**Comment by mike6321** [comment]
넵넵 확인 했습니다~ 도움주셔서 감사합니다.
